"use client";

import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { Minus, Plus, X } from "lucide-react";
import type { CatalogProduct } from "@/lib/catalog";
import { ImageOrIcon } from "@/components/shop/ImageOrIcon";

export type CartLine = { product: CatalogProduct; quantity: number };

export function CartDrawer({ isOpen, onClose, lines, onChangeQuantity }: { isOpen: boolean; onClose: () => void; lines: CartLine[]; onChangeQuantity: (productId: string, delta: number) => void }) {
  const subtotal = lines.reduce((sum, line) => sum + line.product.sellPrice * line.quantity, 0);
  return <AnimatePresence>{isOpen && <><motion.button initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose} aria-label="Close cart overlay" className="fixed inset-0 z-[60] bg-slate-950/60 backdrop-blur-sm" /><motion.aside initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", damping: 28, stiffness: 260 }} className="fixed right-0 top-0 z-[70] flex h-full w-full max-w-md flex-col bg-white p-6 shadow-2xl dark:bg-[#080d1a]"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-600">Your bag</p><h2 className="mt-1 text-2xl font-black text-slate-950 dark:text-white">কার্ট</h2></div><button onClick={onClose} aria-label="Close cart" className="grid size-10 place-items-center rounded-xl bg-slate-100 dark:bg-white/10"><X size={19} /></button></div><div className="mt-8 flex-1 space-y-4 overflow-y-auto">{lines.map(({ product, quantity }) => <div key={product.id} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4 dark:border-white/10">  <span className={`grid size-14 place-items-center overflow-hidden rounded-xl bg-gradient-to-br ${product.accent} p-1 text-3xl`}><ImageOrIcon src={product.images[0] ?? product.icon} alt="" sizes="56px" className="size-full object-contain" /></span><div className="min-w-0 flex-1"><p className="truncate font-bold text-slate-900 dark:text-white">{product.name}</p><p className="mt-1 text-sm text-slate-500">৳{product.sellPrice.toLocaleString("en-BD")}</p><div className="mt-2 inline-flex items-center rounded-lg border border-slate-200 dark:border-white/10"><button onClick={() => onChangeQuantity(product.id, -1)} className="grid size-7 place-items-center"><Minus size={13} /></button><span className="w-7 text-center text-xs font-bold">{quantity}</span><button onClick={() => onChangeQuantity(product.id, 1)} className="grid size-7 place-items-center"><Plus size={13} /></button></div></div><p className="font-black text-slate-900 dark:text-white">৳{(product.sellPrice * quantity).toLocaleString("en-BD")}</p></div>)}</div><div className="border-t border-slate-200 pt-5 dark:border-white/10"><div className="mb-4 flex justify-between text-lg font-black text-slate-950 dark:text-white"><span>সাবটোটাল</span><span>৳{subtotal.toLocaleString("en-BD")}</span></div><Link onClick={onClose} href="/checkout" className="block rounded-xl bg-cyan-500 px-5 py-3.5 text-center text-sm font-black text-slate-950 transition hover:bg-cyan-300">অর্ডার সম্পন্ন করুন</Link></div></motion.aside></>}</AnimatePresence>;
}
